### ISSUE TITLE
error building kf5-sonnet

### ISSUE THREAD

**Issue by yurikoles** [haraldF/homebrew-kf5#99]
stable https://gist.github.com/ea66503e9f0025ff3fee542acd682f70
head https://gist.github.com/920b055910f0d360bcf5d5487f385be1
Upstream issue https://bugs.kde.org/show_bug.cgi?id=377933

**Comment by wtianyi** [comment]
The upstream have claimed that the bug was fixed in version 5.34.0, which is exactly what is currently used by the formulas.

However I still encounter the similar error:
[https://gist.github.com/wtianyi/d88ec970596676a9f6fc8d306186de10](https://gist.github.com/wtianyi/d88ec970596676a9f6fc8d306186de10)

I'm not sure but should the `kde_enable_exceptions()` in `extra-cmake-modules/kde-modules/KDECompilerSettings.cmake` or something be enabled so that the compile option `-fexceptions` instead of `-fno-exceptions` is used?

How can I test whether modifications like this work or not easily? Currently I am trying to compile the kf5-sonnet myself by copy&paste the commands in `02.make` in Homebrew's logs of kf5-sonnet. But errors came:
```
CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "Qt5" (requested
  version 5.6.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
```

Clearly Homebrew could settle it automatically, but as a newbie I am not sure how to set `Qt5` (and potentially other things) for the compilation properly and manually.

**Comment by yurikoles** [comment]
Same issue here: https://gist.github.com/5577c5eecf3fcb089f4e5ca4f29fdb15

**Comment by yurikoles** [comment]
@haraldF is this fix is mainlined upstream?

**Comment by haraldF** [comment]
@yurikoles - see https://git.reviewboard.kde.org/r/130138/
